name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.2.20176.6
    - name: Install dependencies
      run: dotnet restore ./src/Blazor.AdminLte
    - name: Build
      run: dotnet build ./src/Blazor.AdminLte --configuration Release --no-restore
#    - name: Test
#      run: dotnet test ./src/Blazor.AdminLte --no-restore --verbosity normal


# Generate the website
#    - name: Publish
#      run: dotnet publish ./src/GitHubPages/GitHubPages.csproj --configuration Release
# Publish the website
#    - name: GitHub Pages action
#      if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
#      uses: peaceiris/actions-gh-pages@v3.6.1
#      with:
#        github_token: ${{ secrets.PUBLISH_TOKEN }}
#        publish_branch: gh-pages
#        publish_dir: /src/GitHubPages/bin/Release/netstandard2.1/wwwroot
#        allow_empty_commit: false
#        keep_files: false
#        force_orphan: true
      # Set custom domain name
#        cname: blazorize-adminlte.morstead.nl
